"""initial migration

Revision ID: 2ebe568cb944
Revises: 
Create Date: 2025-12-14 11:16:35.292567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ebe568cb944'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('planes',
    sa.Column('plane_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('plane_id')
    )
    op.create_table('states',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('cities',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('aeroports',
    sa.Column('aeroport_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['cities.code'], ),
    sa.ForeignKeyConstraint(['state'], ['states.code'], ),
    sa.PrimaryKeyConstraint('aeroport_id')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('destiny', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('departure', sa.DateTime(), nullable=False),
    sa.Column('arriving', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('weather', sa.Enum('CHOVENDO', 'ENSOLARADO', 'NUBLADO', 'LIMPO', 'TEMPESTADE', name='weather_enum'), nullable=True),
    sa.Column('plane', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destiny'], ['cities.code'], ),
    sa.ForeignKeyConstraint(['origin'], ['cities.code'], ),
    sa.ForeignKeyConstraint(['plane'], ['planes.plane_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_birth', sa.Date(), nullable=False),
    sa.Column('user_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_city', sa.Integer(), nullable=False),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wish_country_one', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wish_country_two', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wish_country_three', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('travel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_city'], ['cities.code'], ),
    sa.ForeignKeyConstraint(['user_country'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['user_state'], ['states.code'], ),
    sa.ForeignKeyConstraint(['wish_country_one'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['wish_country_three'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['wish_country_two'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('seats',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weather', sa.Enum('ECONOMY', 'P_ECONOMY', 'BUSINESS', 'FIRST_CLASS', name='class_types_enum'), nullable=True),
    sa.Column('location', sa.Enum('WINDOWS', 'CORRIDOR', 'MIDDLE', 'EMERGENCY', 'WING', 'FRONT', name='seat_place_enum'), nullable=True),
    sa.Column('location_especify', sa.Enum('WINDOWS', 'CORRIDOR', 'MIDDLE', 'EMERGENCY', 'WING', 'FRONT', name='seat_place_especify_enum'), nullable=True),
    sa.Column('plane_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plane_id'], ['planes.plane_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('seat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    op.drop_table('users')
    op.drop_table('flights')
    op.drop_table('aeroports')
    op.drop_table('cities')
    op.drop_table('states')
    op.drop_table('planes')
    op.drop_table('countries')
    # ### end Alembic commands ###
