"""initial migration

Revision ID: 78247e68f597
Revises: 
Create Date: 2025-11-20 08:38:02.468252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78247e68f597'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('state',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('city',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['state.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wish_country_one', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wish_country_two', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wish_country_three', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('travel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_city'], ['city.code'], ),
    sa.ForeignKeyConstraint(['user_country'], ['country.code'], ),
    sa.ForeignKeyConstraint(['user_state'], ['state.code'], ),
    sa.ForeignKeyConstraint(['wish_country_one'], ['country.code'], ),
    sa.ForeignKeyConstraint(['wish_country_three'], ['country.code'], ),
    sa.ForeignKeyConstraint(['wish_country_two'], ['country.code'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=90), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('user_nickname', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('user_phone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('user_birth', sa.DATE(), nullable=False),
    sa.Column('user_country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_state', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_creation', sa.DATE(), nullable=False),
    sa.Column('user_lastSeen', mysql.DATETIME(), nullable=False),
    sa.Column('user_accountStatus', mysql.ENUM('active', 'inactive', 'banned'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('user_wishCountryOne', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_wishCountryTwo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_wishCountryThree', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_travelType', mysql.ENUM('lazer', 'negocios', 'aventura', 'cultural', 'gastronomica', 'outros'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('country')
    # ### end Alembic commands ###
