"""added flight related (seat, flight, plane, aeroport) & fix on other tabels FKs

Revision ID: 94440ff98cac
Revises: 78247e68f597
Create Date: 2025-11-20 10:07:31.074882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '94440ff98cac'
down_revision: Union[str, Sequence[str], None] = '78247e68f597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plane',
    sa.Column('plane_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('plane_id')
    )
    op.create_table('seat',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plane_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plane_id'], ['plane.plane_id'], ),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_table('aeroport',
    sa.Column('aeroport_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['city.code'], ),
    sa.ForeignKeyConstraint(['state'], ['state.code'], ),
    sa.PrimaryKeyConstraint('aeroport_id')
    )
    op.create_table('flight',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destiny', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('departure', sa.DateTime(), nullable=False),
    sa.Column('arriving', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('weather', sa.Enum('CHOVENDO', 'ENSOLARADO', 'NUBLADO', 'LIMPO', 'TEMPESTADE', name='weatherenum'), nullable=True),
    sa.Column('plane', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destiny'], ['city.code'], ),
    sa.ForeignKeyConstraint(['origin'], ['city.code'], ),
    sa.ForeignKeyConstraint(['plane'], ['plane.plane_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.alter_column('user', 'user_birth',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_birth',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('flight')
    op.drop_table('aeroport')
    op.drop_table('seat')
    op.drop_table('plane')
    # ### end Alembic commands ###
