"""fixes

Revision ID: 9d8bf82ca4e0
Revises: f37c57f7344f
Create Date: 2026-01-24 09:29:01.987210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8bf82ca4e0'
down_revision: Union[str, Sequence[str], None] = 'f37c57f7344f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_ibfk_4'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_ibfk_5'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_ibfk_6'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_ibfk_6'), 'users', 'countries', ['wish_country_two'], ['code'])
    op.create_foreign_key(op.f('users_ibfk_5'), 'users', 'countries', ['wish_country_three'], ['code'])
    op.create_foreign_key(op.f('users_ibfk_4'), 'users', 'countries', ['wish_country_one'], ['code'])
    # ### end Alembic commands ###
